### ISSUE TITLE
Feature Request: Keep existing tokens when configuring rclone.conf using this role

### ISSUE THREAD

**Issue by hkcomori** [stefangweichinger/ansible-rclone#101]
Google Drive tokens will be changed by reconnect.
The tokens will be broken if this role is rerun.

To prevent this, I have to rewrite tokens in the playbook every time I reconnect.

I want options to keep existing tokens.

It seems difficult to manage tokens separately with Rclone's features.

https://forum.rclone.org/t/include-stuff-from-other-files-in-the-rclone-conf-file/21003

**Comment by stefangweichinger** [comment]
I don't use google drive, so I won't be much help here. Maybe @jackodsteel knows how to solve this, he contributed #36 etc

**Comment by stefangweichinger** [comment]
That's as I understand and assume it as well. Thanks @jackodsteel for the quick reply.

**Comment by hkcomori** [comment]
Sorry, I was wrong about the token being broken.
As @jackodsteel said, there is no issue here.

The reason for my issue was that I didn't set `expiry` for the role.

- The role will write the old token (expired) to the target host.
- Rclone will use `refresh_token` to update the token. This does not seem to work without `expiry`.

I think the operation of overwriting with an old token is unnecessary.
But, it is not a problem in use.

Thank you for your support.
