### ISSUE TITLE
Installing Beta fails with rclone_version

### ISSUE THREAD

**Issue by agncr** [stefangweichinger/ansible-rclone#102]
I've tried to install the beta version of rclone and it failed. 
- Set `rclone_version=beta` for host (see Readme)
- fatal: [xxx]: FAILED! => {"changed": false, "msg": "Failure downloading https://downloads.rclone.org/vbeta/rclone-vbeta-linux-amd64.zip, HTTP Error 404: Not Found"}
- Set `rclone_release=beta` for host
- Beta installed

**Comment by stefangweichinger** [comment]
Seems the README is wrong.

Don't set `rclone_version=beta`, only `rclone_release=beta` and re-test.

If it succeeds, I will change the README accordingly. Thanks for reporting.

**Comment by agncr** [comment]
Setting `rclone_release=beta` installs the beta version.

**Comment by stefangweichinger** [comment]
@agncr  Is that a "success" feedback?

**Comment by agncr** [comment]
Yep, success feedback.

**Comment by stefangweichinger** [comment]
I will check the code in detail if the logic really works like I remember ... and prepare a PR for `README.md`.
