### ISSUE TITLE
Unable to set ownership on config directory / file for rclone

### ISSUE THREAD

**Issue by theonewizard** [stefangweichinger/ansible-rclone#116]
Hi

Role runs as root and config files is set to be owned by root only. Please consider giving the option to change the ownership.

**Comment by theonewizard** [comment]
default/main.yml:

rclone_config_owner:
  OWNER: root
  GROUP: root

- name: Install configs
  block:
    - name: Create config directory
      file:
        path: '{{ rclone_config_location | dirname }}'
        state: directory
        owner: '{{ rclone_config_owner.OWNER }}'
        group: '{{ rclone_config_owner.GROUP }}'
        mode: '0700'

    - name: Set up rclone config
      template:
        src: rclone.conf.j2
        dest: '{{ rclone_config_location }}'
        owner: '{{ rclone_config_owner.OWNER }}'
        group: '{{ rclone_config_owner.GROUP }}'
        mode: 0600
  become: true
  when: rclone_configs is defined

**Comment by stefangweichinger** [comment]
Why did you close https://github.com/stefangweichinger/ansible-rclone/pull/117 ?

**Comment by theonewizard** [comment]
Hi Stefan!

I am new to this so I thought it was the thing to do. I have reopened it.

**Comment by stefangweichinger** [comment]
No problem. I think it would be great to also document your new variables in the README, right? thanks for your contribution

**Comment by theonewizard** [comment]
Yes absolutely and you are welcome.

**Comment by stefangweichinger** [comment]
You know that I expect you to add the changes to the README to your PR, right? ;-)
