### ISSUE TITLE
Add support for beta version

### ISSUE THREAD

**Issue by mjmayer** [stefangweichinger/ansible-rclone#12]
One of the common requests when submitting a bug report to rclone is to install the latest beta.

The latest beta for rclone can be found at https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip , however when this file is unarchived, the directory it creates is in the format of {Version Tag}-{Commit Number}-g{Git Commit Hash}. In your playbook, you assume that rclone will be extracted to the path '/tmp/rclone_setup/rclone-v{{ rclone_version }}-linux-amd64'. 

I see two ways to work around this. We could keep your existing code and put it in a block that runs when rclone_version != "beta". Then add a new block for the beta version that includes some logic to find out the name of the directory that is created in the unarchive step. Alternatively, we could discard the creates option  and determine the folder created in the unarchive step. Then use the path of the folder created in the unarchive step in the rest of the playbook.

Do you have a preferred solution or any other ideas? I can start working on a pull request once I have your input.

**Comment by stefangweichinger** [comment]
sry, busy at the moment, will get back to you in the next days. Thanks for the PR so far!

**Comment by stefangweichinger** [comment]
Haven't tested your patch yet, only read it: looks good to me.
An additional idea in this context (and rather easy to implement IMO): why not add 

```
rclone_version: "stable"
```
as well?

meaning -> it installs the latest stable release.

**Comment by stefangweichinger** [comment]
closed by merging #13 
thanks for contributing
