### ISSUE TITLE
Config directory mode

### ISSUE THREAD

**Issue by pixelrebel** [stefangweichinger/ansible-rclone#131]
There is no reason to set the config directory to `700`.  When installing in a very common location like `/etc/rclone.conf`, the role hoses the mode of the `/etc` directory and breaks a lot of stuff. `755` is a perfectly reasonable mode for a config directory as long as the file is set to `600`.

**Comment by stefangweichinger** [comment]
Good observation, although we install to `/root/.config/rclone` per default and not to `/etc`. But yes, if you change that to `/etc`, that breaks things. I will come up with a PR soon. Thanks.
