### ISSUE TITLE
Galaxy role is out of date

### ISSUE THREAD

**Issue by finchd** [stefangweichinger/ansible-rclone#14]
PR #13 was merged here 4 months ago, adding support for the beta releases, but Galaxy hasn't been triggered to import the new version of the role.

Please tag a GitHub release and import into Galaxy.

Though if you want, it looks like Travis-CI integration webhooks are how Galaxy does automatic updates [here.]( https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#travis-integrations )

**Comment by stefangweichinger** [comment]
thanks for the pointer, did some release: 
https://github.com/stefangweichinger/ansible-rclone/releases/tag/v1.42

Will look up how to do the next steps, for now I consider the webhook-method a bit of an overkill (?)

**Comment by stefangweichinger** [comment]
Thanks for the help, I can't even remember any galaxy login ;-) ... that was long ago.
I will try my best to get that working.

**Comment by stefangweichinger** [comment]
Re-imported role into galaxy so you can use it from there now.
That Travis-CI-issue ... I logged in there but didn't understand that fully yet ... but at least I created the repo in there, maybe that's enough already?
