### ISSUE TITLE
Check run fails

### ISSUE THREAD

**Issue by burner1024** [stefangweichinger/ansible-rclone#140]
Dry run fails:
```
$ ansible-playbook -l testhost -t rclone -C site.yml
...
TASK [stefangweichinger.ansible_rclone : Get rclone stable version 1.63.1] ************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [testhost]: FAILED! => {"changed": false, "msg": "dest '/tmp/rclone_setup' must be an existing dir"}
```

**Comment by stefangweichinger** [comment]
Well, if you do a dry run nothing is changed, so the tempdir isn't created and doesn't exist later. 

As intended: you told ansible not to do anything to your target system.

This is more of a cosmetic issue, I'd say. And I tend to think that it's not worth programming a beautiful workaround for this test-case.

Sure, one could add when-clauses for the test-case and a more explicit explanation.
PRs welcome, if you really need this.
