### ISSUE TITLE
maintenance todos

### ISSUE THREAD

**Issue by stefangweichinger** [stefangweichinger/ansible-rclone#143]
Some notes here:
the whole testing and releasing takes even more effort than the actual role ;-)

* ansible-galaxy seems to want a release-number > 1: that's still not the case in this repo, I assume I have to do that in a next step. Right now I skip the related test in ansible-lint
* because the release-number wasn't changed, the latest changes didn't yet get released to galaxy
* the action we use for linting is outdated: has to be replaced: https://github.com/marketplace/actions/run-ansible-lint
* I added `meta/runtime.yml` to make ansible-lint happy. The content was taken from an example, it's not correct.

**Comment by stefangweichinger** [comment]
github-action for linting changed in 06924afad4d815d7b8c18df6991d29db80116d39

**Comment by stefangweichinger** [comment]
* semantic versioning: I understand the point of doing that, but I still don't know how to properly use `commitizen` ... the repository still isn't fully commitizen-friendly. I have to learn this. And then maybe bump the version to 1.0.0 to make ansible-galaxy even happier.

**Comment by stefangweichinger** [comment]
0.1.3 released and imported into ansible-galaxy from the shell: the gh-action doesn't work right now

**Comment by tigattack** [comment]
Hey @stefangweichinger, regarding the Galaxy action which I also saw discussed in #147, perhaps this alternative approach is of interest to you? https://github.com/tigattack/ansible-role-mergerfs/blob/main/.github/workflows/release.yml

**Comment by stefangweichinger** [comment]
> Hey @stefangweichinger, regarding the Galaxy action which I also saw discussed in #147, perhaps this alternative approach is of interest to you? https://github.com/tigattack/ansible-role-mergerfs/blob/main/.github/workflows/release.yml

Thanks a lot, I'll have a closer look asap.

**Comment by stefangweichinger** [comment]
currently the release-step works again (phew!), so I close here just to keep things clean. thanks for the pointer @tigattack
