### ISSUE TITLE
Install binary for non root user

### ISSUE THREAD

**Issue by hkcomori** [stefangweichinger/ansible-rclone#153]
I want to install rclone in the home directory of non-root user for personal use on a shared machine. (eg. `~/.local/bin/rclone`)
For this purpose, I'm happy if the binary `location`, `owner,` and `group` could be specified by variables.

The binary `location` will be able to specified by #65, but no other variables.
It would be more consistent if `location`, `owner`, and `group` for binary could be changed, because config already allows same parameters to be changed.

I would also prefer that `become: true` be managed outside of the role, so that it can be executed by a non-root user.

Are such use cases acceptable in this role?

**Comment by stefangweichinger** [comment]
Well, it's opensource and open to patches and PRs ;-) 

* location/owner/group: sure, why not enhance the role?
* become: I'd have to think about it in more detail

I won't be able to do much work on this in the next weeks or so. If you come up with a PR or two, it's very much appreciated. The suggested enhancements would fit the scope of the role IMO.

**Comment by hkcomori** [comment]
Thanks for the response.
I considered modifying it, but it seems to conflict with #65.
#65 has remained unmerged for a long time, is there any chance it will be merged in the future?

**Comment by stefangweichinger** [comment]
phew, #65 was a draft and abandoned. I'd have to look at it again.
Currently I don't have much time for it, real life issues, work etc

**Comment by stefangweichinger** [comment]
I suggest you base your patches on the `main` branch ... or try to improve #65 maybe. As I said: I can't tell if #65 still makes sense right now. But maybe it would be good to continue there.

**Comment by stefangweichinger** [comment]
@hkcomori still interested in contributing?

#65 was a start but I assume the bigger part of it should be thrown away.
The idea was to add a toggle to "simply" install `rclone` from the official repos of each distribution instead of taking it from the rclone-project-site. 

Adding the three variables shouldn't be that hard, I think. We could base it on #65 and start from there.

**Comment by hkcomori** [comment]
Sorry, still interested but too busy to do much work on it.

Thanks, then I'll modify it, referring to the implementation of #65, but not worrying about conflicts though.
But my motivation is installation by non-root user, so I want to consider stopping `become: true` first.

**Comment by hkcomori** [comment]
I found some issues for non-root users to use this role.
This is going to be a bigger change than I expected.

**1. Cannot create file directory for local fact**

- /etc/ansible/facts.d
- /etc/ansible/facts.d/rclone

We need to find another method.

**2. Cannot perform some operations related to mounts**

- Create symbolic link for fusermount
- Create systemd service

In my opinion, these features can be skipped, because they are not needed for non-root users.
