### ISSUE TITLE
Consider adding this to Ansible Galaxy

### ISSUE THREAD

**Issue by lonix** [stefangweichinger/ansible-rclone#2]
Consider adding this module to ansible galaxy.

**Comment by nfaction** [comment]
Agreed. My PR#6 adds better OS support as well as full-stack Travis testing.

Hope this helps!

**Comment by stefangweichinger** [comment]
Will review PR#6 asap, thanks!
ad galaxy: I have to read their howto first ...

**Comment by stefangweichinger** [comment]
have a look at https://galaxy.ansible.com/stefangweichinger/rclone/
I will maybe add Gentoo Linux as well, got to check the dependencies there.

**Comment by stefangweichinger** [comment]
added to galaxy, issue closed
