### ISSUE TITLE
Change /usr/sbin/rclone to /usr/bin/rclone

### ISSUE THREAD

**Issue by emilstahl** [stefangweichinger/ansible-rclone#4]
/usr/sbin/ is not in the default path on Debian 8.5 or Cent OS 7.

Why not change it to `/usr/bin`?

CentOS Linux release 7.2.1511
`/usr/local/bin:/usr/bin`

Ubuntu 16.04.1 LTS
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games`

Debian GNU/Linux 8.5 (jessie)
`/usr/local/bin:/usr/bin:/bin:/usr/games`

**Comment by emilstahl** [comment]
I learned something new today :)

**Comment by zogthealien** [comment]
@emilstahl and what is that?
