### ISSUE TITLE
Support for Ubuntu derivated distributions

### ISSUE THREAD

**Issue by tangel0v** [stefangweichinger/ansible-rclone#51]
Hi Stephan

I have been using your role for last year and it's great: simple and efficient, but I have upgraded my laptop from PopOS 19.10 to PopOS 20.04 and I have detected it has stopped working.

The problem is located in the data received by Ansible in _ansible\_distribution_ vars. PopOS and other Ubuntu derivated distros sometimes modify the content of /etc/os-release. For example: the content of my ansible_distribution is "Pop!_OS" therefore task "Gather OS specific variables" fails with the following error:

_"msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found_

I want to change this behaviour to use _ansible_distribution_release_ instead of using _ansible_distribution_, covering all Linux distrubutions based in Ubuntu.

Will you accept a PR with this feature? I'll add support for Ubuntu 20.04 too.

Thank you very much

**Comment by stefangweichinger** [comment]
Hm, that sounds like a big change hitting all the distros.
I suggest you file the PR and we will see how the molecule tests work out.
After that we might discuss ...

Why not add a specific file in `./vars` for a start?

**Comment by tangel0v** [comment]
Yes, I am agree with you I'll start adding the file in vars

**Comment by tangel0v** [comment]
Which version of molecule are you using? I have been receiving one error and I want to check the tests before creating the PR.

**Comment by stefangweichinger** [comment]
my local system:

```
molecule --version
molecule 3.0.4
   ansible==2.9.6 python==3.8
```

Travis doesn't show the version, I might add above command to the playbook for reference.

**Comment by stefangweichinger** [comment]
support and test for Ubuntu 20.04 added in fb2d65757759877a4cb2a4ca4e03b591155570c9

**Comment by tangel0v** [comment]
Ok stefan, I'll create different PR today.

**Comment by tangel0v** [comment]
New PR: https://github.com/stefangweichinger/ansible-rclone/pull/54
