### ISSUE TITLE
Fails when Rclone is already latest version

### ISSUE THREAD

**Issue by djarbz** [stefangweichinger/ansible-rclone#58]
It appears to have failed for me when there is no new version of Rclone.

```
TASK [stefangweichinger.ansible_rclone : Do stable install] *************************************************************************************************************************
Saturday 24 October 2020  18:17:02 +0000 (0:00:00.264)       0:05:37.275 ****** 
included: /home/ansible/.ansible/roles/stefangweichinger.ansible_rclone/tasks/stable.yml for RCLONE_HOST

TASK [stefangweichinger.ansible_rclone : Check latest stable rclone version number] *************************************************************************************************
Saturday 24 October 2020  18:17:02 +0000 (0:00:00.227)       0:05:37.503 ****** 
ok: [RCLONE_HOST]

TASK [stefangweichinger.ansible_rclone : Set variable to latest stable version number] **********************************************************************************************
Saturday 24 October 2020  18:17:04 +0000 (0:00:01.543)       0:05:39.046 ****** 
ok: [RCLONE_HOST]

TASK [stefangweichinger.ansible_rclone : Get rclone stable version 1.53.1] **********************************************************************************************************
Saturday 24 October 2020  18:17:04 +0000 (0:00:00.240)       0:05:39.287 ****** 
skipping: [RCLONE_HOST]

TASK [stefangweichinger.ansible_rclone : Do beta install] ***************************************************************************************************************************
Saturday 24 October 2020  18:17:04 +0000 (0:00:00.154)       0:05:39.441 ****** 
skipping: [RCLONE_HOST]

TASK [stefangweichinger.ansible_rclone : Copy rclone binary] ************************************************************************************************************************
Saturday 24 October 2020  18:17:04 +0000 (0:00:00.062)       0:05:39.504 ****** 
fatal: [RCLONE_HOST]: FAILED! => {"changed": false, "msg": "Source /tmp/rclone_setup/rclone-v1.53.1-linux-amd64/rclone not found"}
```

**Comment by stefangweichinger** [comment]
More details, please.
What variables do you set?
There is a version of rclone already installed or what?
I don't get the full picture yet.

**Comment by djarbz** [comment]
This is how I call your role.
```
- name: Install & configure rclone
  include_role:
    name: stefangweichinger.ansible_rclone
  vars:
    rclone_config_location: "/etc/rclone/rclone.conf"
    rclone_configs: "{{ hostvars[inventory_hostname].rclone_config }}"
  when: rclone_key.stat.exists
```

I just ran the playbook again and it worked without issue.

I had already ran your playbook, had rclone running for a few weeks.
Ran the playbook again and I got the log output above.
It looks to me as if your role recognizes that Rclone is installed and latest, but still attempts to install/copy the binary even though the download was skipped.

**Comment by stefangweichinger** [comment]
The task `Get rclone stable version` should only be skipped if `/tmp/rclone_setup/rclone-v1.53.1-linux-amd64/rclone` already exists. And this should result in the working copy ...

Please re-run with more debugging ("-vv" or so).

And check what happens in `/tmp/rclone_setup`. As far as I understand it should either overwrite or re-create, and after that the copy should find the source file.

Please also report the used version of ansible. Maybe the behavior of the module(s) has changed slightly.

**Comment by stefangweichinger** [comment]
Maybe we should simply remove the parameter `creates` from the last line of `tasks/stable.yml`.
You are the first user to report this problem, though.

**Comment by djarbz** [comment]
I think we should close this issue for now and chalk it up as a fluke.
I'm not sure why "Get rclone stable version" was skipped as the logic would not skip it.

I will re-open if I have further issues, but I cannot re-create the issue any longer.

**Comment by stefangweichinger** [comment]
OK, fine with me. Feel free to re-open if you hit it again.
