### ISSUE TITLE
molecule tests fail for beta-version

### ISSUE THREAD

**Issue by stefangweichinger** [stefangweichinger/ansible-rclone#66]
I noticed at a test run of the Github Action "Molecule" that all jobs setting `rclone_version: beta` fail right now.

I don't have the time to debug this *now*, maybe the format of the version has changed upstream or something like that.

`rclone_version: stable` tests OK, that should be the default use case anyway.

For reference the link to the failed run: https://github.com/stefangweichinger/ansible-rclone/actions/runs/358605739

**Comment by stefangweichinger** [comment]
OK, got it:

currently there is a mismatch between https://beta.rclone.org/version.txt and https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip

version.txt says : "1.54.0-beta.4903.211b08f77"

the zip-file contains : rclone-v1.53.3-linux-amd64

Not our bug.

**Comment by stefangweichinger** [comment]
@mjmayer : maybe you are interested in this one because you contributed beta-installation in #12 

We might add some check code: compare the version we read from version.txt with the directory created by the unzip.
But we can only fail there and report it, I don't see how to really work around this case right now.

I assume that it won't happen that often anyway.

**Comment by stefangweichinger** [comment]
https://github.com/stefangweichinger/ansible-rclone/pull/67

.. some debug statements show the content of the zip-file etc

```
TASK [ansible-rclone : debug rclone_version] ***********************************
    ok: [instance] => {
        "rclone_version": "1.54.0-beta.4903.211b08f77"
    }
    
    TASK [ansible-rclone : Get rclone latest beta version] *************************
    changed: [instance]
    
    TASK [ansible-rclone : print unarchived folder list of files] ******************
    ok: [instance] => {
        "msg": [
            "rclone-v1.53.3-linux-amd64/",
            "rclone-v1.53.3-linux-amd64/README.html",
            "rclone-v1.53.3-linux-amd64/rclone.1",
            "rclone-v1.53.3-linux-amd64/rclone",
            "rclone-v1.53.3-linux-amd64/README.txt",
            "rclone-v1.53.3-linux-amd64/git-log.txt"
        ]
    }
```

**Comment by mjmayer** [comment]
I agree the best we can do here is to compare `rclone_version` to what is actually unarchived. Then we can fail with a useful error message for the user.

**Comment by stefangweichinger** [comment]
Yes. Any idea how to grep that out of this "msg" ?
