### ISSUE TITLE
errors when installing on jessie

### ISSUE THREAD

**Issue by nbonfire** [stefangweichinger/ansible-rclone#7]
I got errors using this as-is on a fresh install of debian jessie.

I needed to change the man path to /usr/share/man/man1 and man_group to "root" instead of "staff".

**Comment by stefangweichinger** [comment]
this means that the main task has to be rewritten to reflect different paths for manpages (some work).
plus editing vars/Debian.yml (easy).

Don't you want to come up with some PR for that? ;-)

**Comment by nbonfire** [comment]
I wouldn't mind, but I don't understand the discrepancy. Which release of debian was this written for originally?

**Comment by stefangweichinger** [comment]
pls check above PR (untested)
I can't remember exactly, might be that I copied some role structure back then ... without testing on all distros.

**Comment by nbonfire** [comment]
works for me

**Comment by stefangweichinger** [comment]
great, thanks for reporting and testing. So I should merge that asap ;-)
