### ISSUE TITLE
Role still downloading archive when rclone already installed

### ISSUE THREAD

**Issue by isavcic** [stefangweichinger/ansible-rclone#80]
Hello, I've noticed that the role downloads the rclone archive again and again, even when it downloaded and installed it successfully the first time around. Is this intentional? Thanks.

**Comment by stefangweichinger** [comment]
Just a quick reply, I would have to look in detail: there was an issue with the temporary directory etc / there we decided to pull the archiv every time. It's somewhere in the other issues, I'll try to reconstruct the *why* in the next days.

**Comment by isavcic** [comment]
Maybe separate the install tasks from the main, have them save the fact of the version that got installed and include the tasks installed when:
```
- name: Perform the install steps
  include_tasks: install.yml
  when: (ansible_facts['ansible_local']['rclone'] is not defined) or (ansible_facts['ansible_local']['rclone']['rclone']['installed_version'] != rclone_version)
```

**Comment by stefangweichinger** [comment]
I just looked at the commits and think this one is responsible for the mentioned behavior: https://github.com/stefangweichinger/ansible-rclone/commit/40ef4cf490ac3be232035799cd99428fb755065d

Can't remember 100% what was the reason back then.

I will consider your suggestion, thanks.

**Comment by stefangweichinger** [comment]
@isavcic I started to fiddle with facts in a local branch but I don't have much experience with handling them. Would you mind going into more detail with your suggestion?

**Comment by isavcic** [comment]
I created a pull request based on modifications made. #81

**Comment by stefangweichinger** [comment]
@isavcic see my WIP at https://github.com/stefangweichinger/ansible-rclone/compare/issue80
I consulted the ansible-guru @drybjed and copied his approach to dynamically get the facts from the instance.
Seems to work mostly, although testing in molecule seems to cache the facts, which makes it hard to test the re-run.
I will continue improving this.

**Comment by stefangweichinger** [comment]
My fact-getting script seems not work correctly for all distros. Further tests needed.

**Comment by isavcic** [comment]
Can you provide the error output here?

**Comment by stefangweichinger** [comment]
> Can you provide the error output here?

When I run the tests in molecule my debug task(s) show that the returned variables of the fact script are:

```
TASK [ansible-rclone : Re-read facts after adding custom fact] *****************
ok: [instance]

TASK [ansible-rclone : print ansible_facts vars] *******************************
ok: [instance] => {
    "ansible_facts.ansible_local": {
        "rclone": {
            "configured": true,
            "installed": false
        }
    }
}
```

This is at the second run: the fact script is in place, and also the rclone binary, so it should return "true" for "installed".

If I enter the container and execute the script it returns "true" ->

```
[root@instance /]# /etc/ansible/facts.d/rclone.fact 
{
    "configured": true, 
    "installed": true, 
    "installed_version": "1.54.0"
}
```

as it should. It seems as if the centos-container behaves different, maybe some difference in the available python? Or the $PATH?

From these variables I plan to decide if to install .. you know.

**Comment by isavcic** [comment]
Do you have the generated fact at hand from those failing containers?

**Comment by stefangweichinger** [comment]
I don't understand. Isn't it the 1st quote above?

**Comment by isavcic** [comment]
Oh, I'm sorry if I was unclear; do you have the generated Python fact script?

**Comment by drybjed** [comment]
This might not be an issue with the script but with fact gathering process. The output of `ansible_facts.ansible_local` suggests that the `setup` module or fact gathering process was started with unprivileged account, or with `become_user` to an unprivileged account. It's running via `molecule`, correct? Did you tell it to switch to `root` right away?

**Comment by stefangweichinger** [comment]
@drybjed I don't know ;-) I assume you and we talk of the playbooks in the molecule subdir.

`converge.yml`  has `become: yes`, `molecule.yml` not, but I read somewhere "The default Molecule Docker driver executes Ansible playbooks as the root user" ( https://github.com/ansible-community/molecule/blob/master/docs/examples.rst ).

For the debian10 instance the fact is returned as `installed: true` with the same scripts.

I added `become: yes` to the setup task in `main.yml`. Same behavior with the centos7 instance, in the 2nd run: `installed: false`.

(I have to tell that I don't have much time or brains in these days to fully focus on this: too much other project work)

**Comment by stefangweichinger** [comment]
some more changes in ceca77dc6f8653d4aca57fbc9ea6f0d6b375cadd and 0dc45fa4d3d6e9745ab181912838d2a5becb85d2

A bit noisy still with all my debug-statements, but the logic seems to work better now.
Although I am currently not sure if the idempotence test works with the github actions. In my local molecule runs it does.

**Comment by stefangweichinger** [comment]
I looked through the logs of the molecule tests, Centos seems to be the one distribution behaving differently. The others seem to work correctly: skip re-installation when rclone is there with the desired `rclone_version`.

**Comment by stefangweichinger** [comment]
@isavcic and @drybjed : could you take a look at my changes, I am a bit unsure if I got the logic right.
I'd feel better with some additional check and test before I clean up my debug messages and merge this.
thanks.

**Comment by isavcic** [comment]
Instead of:
 ```
when: ansible_distribution == 'Ubuntu'
```
IMO you can use
```
when: ansible_os_family == 'Debian'
```
in apt cache update segment, as this will cover Ubuntu and Debian both.

**Comment by stefangweichinger** [comment]
I know that but Ubuntu needs an additional task, so I decided to write it this way. Thanks.

**Comment by stefangweichinger** [comment]
@isavcic were you able to test my draft with one of your systems?

**Comment by isavcic** [comment]
On my Ubuntu 18.04 and Ubuntu 20.04 both it somehow can't detect the latest stable version, task returns 0.0.0 as the version, and of course fails. Weird.

**Comment by stefangweichinger** [comment]
Maybe I have `defaults\main.yml` wrong:

`rclone_version: '{{ ansible_local.rclone.version | d("0.0.0") }}'`

**Comment by stefangweichinger** [comment]
@isavcic yes, thanks. I assume I would need a more meaningful default version in `defaults`. @drybjed suggested that line :-P

**Comment by stefangweichinger** [comment]
@isavcic And now the archive isn't downloaded over and over again? I think it should work, from looking at the molecule logs.

I will apply your patch to my branch and check the molecule tests again.

centos might have some different python version or whatever ... 

I am just cautious, these changes are quite big and I don't want to publish a broken role.
thanks.

**Comment by isavcic** [comment]
I've tested it with manual version specification and leaving it empty, it downloaded rclone once and didn't redownload it, as a matter of fact there were zero changes between the runs.

**Comment by stefangweichinger** [comment]
sounds good

**Comment by stefangweichinger** [comment]
#82 : removed debug-statements, tests running

**Comment by stefangweichinger** [comment]
I merged my changes right now, tests look OK to me.
The detail with the fact-checking in the centos-instances is not yet solved, but doesn't harm as far as I see.
I might open a separate issue for that.

thanks @isavcic  and @drybjed

**Comment by stefangweichinger** [comment]
@isavcic  have a look at #87 as well. Improved logic.
