### ISSUE TITLE
Config file is not updated when rclone_version matches the one already installed

### ISSUE THREAD

**Issue by theenglishway** [stefangweichinger/ansible-rclone#84]
As the title says.. The config file is never updated once rclone has been installed on the remote machine.

I guess it relates to issue #80 and the fix made in #82, that conditions the execution of `install.yml` (which contains the installation of the configuration) to the absence of a rclone whose version matches the specified rclone_version.

It's certainly an improvement that the install process does not run on each role execution, but I would say the rclone_configs is much more likely to change.. Maybe just splitting `install.yml` into a `install-bin.yml` and `install-config.yml` (which would be executed every time) would do the trick ?

**Comment by stefangweichinger** [comment]
Ah, now it starts. I wasn't too happy about #80 and #82 anyway and somehow expected followup issues.

You are right, sure: the config has to be updated. And your suggestions sound good as well. If you like to contribute and suggest a PR, you are welcome. It would be helpful to have a bunch of people developing this role, as we see sometimes things get too complicated for one guy only ;-)

thanks for filing the issue

**Comment by stefangweichinger** [comment]
@theenglishway see above PR, testing welcome

**Comment by theenglishway** [comment]
No time for that today but I'll give it a try tomorrow ! :+1:

**Comment by stefangweichinger** [comment]
I merged and published as it fixes both a functionality issue #84 and a security issue #86.
Feel free to test, comment and reopen here. Thanks.
