### ISSUE TITLE
Use for Update rclone

### ISSUE THREAD

**Issue by rbrueckner82** [stefangweichinger/ansible-rclone#93]
Hello,

how can use this module only to update rclone?

**Comment by stefangweichinger** [comment]
If the installed version on the target host is older than the current upstream version, it should update/reinstall the newer version.
The role does not run "apt-get upgrade" if you look for that.

**Comment by rbrueckner82** [comment]
Yes i look for update/reinstall because apt upgrade not work for rclone.

I will try this, thanks

**Comment by stefangweichinger** [comment]
This role installs by downloading and unpacking the tarballs from upstream.
It does not install from the OS repos via apt/yum/dnf/...
