### ISSUE TITLE
rclone_version: "stable" doesn't seem to work?

### ISSUE THREAD

**Issue by geerlingguy** [stefangweichinger/ansible-rclone#99]
Following the directions in the repository, I tried setting:

```yaml
---
- hosts: backup
  become: true

  vars:
    rclone_arch: "arm64"
    rclone_version: "stable"

  roles:
    - stefangweichinger.ansible_rclone
```

But I get the following error:

```
TASK [stefangweichinger.ansible_rclone : Get rclone stable version stable] *********************************************
fatal: [backup.geerli.net]: FAILED! => {"changed": false, "msg": "Failure downloading https://downloads.rclone.org/vstable/rclone-vstable-linux-arm64.zip, HTTP Error 404: Not Found"}

PLAY RECAP *************************************************************************************************************
backup.geerli.net          : ok=10   changed=3    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0  
```

**Comment by geerlingguy** [comment]
Ah... I was reading the default in the README as needing to be set to `rclone_version: "stable"`, but it looks like that was a misinterpretation. I set it to `rclone_version: ""` and it picked the latest stable release.

**Comment by stefangweichinger** [comment]
Yes, an empty string should work.

IMO setting it to "stable" should also work, but the message you quoted shows that it substitutes the string "stable" and not the version number pulled from upstream.

The relevant part is https://github.com/stefangweichinger/ansible-rclone/blob/21a403bac65dafbe9cb79ac1f2c3dfc51d391440/tasks/main.yml#L39 ... I don't see the mistake on my first view.


(( off-topic: as I read your name in the notification email I thought you reply to a bug that *I* filed in one of your projects ... ;-) ))

**Comment by stefangweichinger** [comment]
```
$  TEST_RELEASE=stable molecule converge
```

also succeeds here. hmmm.

**Comment by stefangweichinger** [comment]
Ah, it should be another "or", right?

Something like:

```
when:
    - rclone_version | length == 0 or rclone_version == "0.0.0" or rclone_release == 'stable'
```

**Comment by geerlingguy** [comment]
Yeah, probably something like that to be sure it ignores the "stable" condition.

**Comment by geerlingguy** [comment]
(And I like to use other people's roles when there's one that looks well-written how I'd like it if I wrote it myself... saves me the work of building it on my own! I'll be using this role for a playbook I use for my backup Pi that I'm finally automating after years of having it run by hand!).

**Comment by stefangweichinger** [comment]
> Yeah, probably something like that to be sure it ignores the "stable" condition.

Would you mind testing my suggested line? Otherwise I will do some tests asap ... maybe tomorrow. As far as I understand you already successfully use the role with ```rclone_version: ""```, right?

**Comment by stefangweichinger** [comment]
> (And I like to use other people's roles when there's one that looks well-written how I'd like it if I wrote it myself... saves me the work of building it on my own! I'll be using this role for a playbook I use for my backup Pi that I'm finally automating after years of having it run by hand!).

I feel kind of honored if you use my role and call it "well-written" ;-) ... thanks. I learned quite some things from reading your molecule-howto, for example, and it's nice to be able to return something this way. Always room for improvement, though ... thanks for reporting this issue.

**Comment by stefangweichinger** [comment]
The debug-task I added above doesn't trigger the error. It tests by setting ```rclone_version: "stable"``` and that works in the molecule test ... results in version 1.55.1 installed currently. Please take a look at the results of the molecule tests -> https://github.com/stefangweichinger/ansible-rclone/actions/runs/1002094368

I am unsure how to proceed. Could it be related to the ansible-version?

**Comment by stefangweichinger** [comment]
@geerlingguy any news on this?

**Comment by geerlingguy** [comment]
@stefangweichinger - Sorry, haven't been able to test it lately because of other priorities. You can feel free to close this as unable to reproduce, and if I find it again I'll try to figure out what's going on then!

**Comment by stefangweichinger** [comment]
@geerlingguy OK, so I close here and hope the best ;-) thanks for the report anyway
